parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    App\UI\Command\:
        resource: '../src/UI/Command'
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@app.command_bus'

    App\Infrastructure\:
        resource: '../src/Infrastructure'
        autowire: true
        autoconfigure: true


    app.command_bus:
        class: App\Application\CommandBus\CommandBus

    App\Application\CommandBus\TestCommandHandler:
        tags:
            - { name: app.command_handler }
