parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    App\UI\Command\:
        resource: '../src/UI/Command'
        autowire: true
        autoconfigure: true
#        bind:
#            $commandBus: '@mmalessa.command_bus'

    App\Infrastructure\:
        resource: '../src/Infrastructure'
        autowire: true
        autoconfigure: true

    App\Application\CommandBus\TestCommandHandler:
        tags:
            - { name: mmalessa.command_handler }
